name: Build and publish tools Docker image

on:
  workflow_dispatch:
    inputs:
      tools_tag:
        description: 'Tools tagged version'
        required: true
      coreperl_tag:
        description: 'Perl libraries tagged version'
        required: true
      tilematrixsets_tag:
        description: 'Tile matrix sets tagged version'
        required: true
        default: '4.2'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: build/tools/
          push: true
          file: build/tools/debian11.Dockerfile
          tags: |
            rok4/tools:${{ github.event.inputs.tools_tag }}
          build-args: |
            ROK4TILEMATRIXSETS_VERSION=${{ github.event.inputs.tilematrixsets_tag }}
            ROK4COREPERL_VERSION=${{ github.event.inputs.coreperl_tag }}
            ROK4TOOLS_VERSION=${{ github.event.inputs.tools_tag }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rok4/tools
          short-description: 'Outils de gestion du projet ROK4 : conversions, suppression de pyramide, calcul de statistiques...'
          readme-filepath: build/tools/README.md